### ISSUE TITLE
Writing greater than 1023 bytes to SDcard at once causes hang

### ISSUE THREAD

**Issue by 0x1d00ffff** [adafruit/Adafruit_CircuitPython_SD#14]
Hey, the following code causes the circuitpython code to hang in the f.write() call. The largest value that completes successfully is 1023 bytes.

```py
with open("/sd/bytes", "wb") as f:
    a = b"\x00" * 1030
    f.write(a)
```

**Comment by 0x1d00ffff** [comment]
I am using `adafruit_sdcard`, yes. This sounds similar but my code hangs *consistently* when trying to write 1024 bytes, or more, at once. I will create an issue there, thanks

**Comment by Anton-2** [comment]
May be related to #25

**Comment by dhalbert** [comment]
We believe #20 fixes this.
