### ISSUE TITLE
In adafruit_sdcard.py, calculate_crc() re-create the CRC table each call, slowing all things down

### ISSUE THREAD

**Issue by Anton-2** [adafruit/Adafruit_CircuitPython_SD#22]
calculate_crc() uses a computed crc_table to speed crc calculation up.

But this crc_table is calculated each time, for each command sent to the card, when it should be calculated once on module loading.

Moving this calculation at modules level helps making adafruit_sdcard.py faster.

**Comment by ladyada** [comment]
oh wow yeah! do you want to try submitting a PR for this, and testing it on your pygamer? then we could merge it in :)

**Comment by Anton-2** [comment]
Done in #23

**Comment by Anton-2** [comment]
Fixed in 21b752883006b91dc251c8778f9f73f9620895db, thanks for merging !
