### ISSUE TITLE
OverflowError: long int not supported in this build

### ISSUE THREAD

**Issue by michelkluger** [adafruit/Adafruit_CircuitPython_SD#27]
When I import this to the Adafruit CircuitPython 5.0.0-alpha.5 on 2019-11-04; Adafruit Feather M0 Adalogger with samd21g18 I get the mentioned error,

OverflowError: long int not supported in this build

Do  you know how I can fix that? Or what might be causing it?

**Comment by dhalbert** [comment]
We have longints turned off on the non-Express builds for space reasons. Could you give me the rest of the error message (line numbers, etc.)? I'll see if there's a possible workaround. This may or may not be related to https://github.com/adafruit/circuitpython/issues/2267

**Comment by michelkluger** [comment]
when I have only the line:

import adafruit_sdcard

 in my main.py, I will get this error already:

OverflowError: long int not supported in this build

**Comment by dhalbert** [comment]
The basic problem is a large constant `0x40000000` in the code. Will see if we can work around this.

EDIT: Yes, we just have to pass the command to the command-sending routine in a different form. I'll work on a PR.
