### ISSUE TITLE
Compatibility Circuitpy/Computer

### ISSUE THREAD

**Issue by davy39** [adafruit/Adafruit_CircuitPython_SD#37]
Hi,
I've been facing a strange behaviour using the library on a Samd21 board and CircutPy5. 
- When I try to read with CircuitPy a text file written from my computer, I only get some x00x00x00x00...
- Same when I try to read with my computer a text file written from CircuitPy -> x00x00x00.
- However, it's OK to read from CircuitPy a file previously written with circuitPy.

Does someone knows why is this happening ?
Thanks for your help !

**Comment by jepler** [comment]
Hi, can you provide any more information?  This sort of problem can occur when the filesystem's not flushed before removing/transferring the SD card, so make sure that's in order.

**Comment by ladyada** [comment]
closing due to lack of response
