### ISSUE TITLE
sdcard demo missing baudrate attribute on Raspberry Pi Pico

### ISSUE THREAD

**Issue by jfabernathy** [adafruit/Adafruit_CircuitPython_SD#42]
After adafruit/circuitpython#4114 was closed, I tested a Pico with adafruit-circuitpython-raspberry_pi_pico-en_US-20210202-9140bfb.uf2 and the latest library bundle as 20210203. I modified the pin numbers in the demo and it still draws an error:
`Traceback (most recent call last):
  File "code.py", line 23, in <module>
  File "adafruit_sdcard.py", line 101, in __init__
  File "adafruit_sdcard.py", line 122, in _init_card
  File "adafruit_sdcard.py", line 111, in _clock_card
AttributeError: 'SPIDevice' object has no attribute 'baudrate'`
My modified demo code is attached:
[code.txt](https://github.com/adafruit/circuitpython/files/5918448/code.txt)

**Comment by dhalbert** [comment]
I will work on fixing this in the library.
