### ISSUE TITLE
storage library

### ISSUE THREAD

**Issue by HourGlss** [adafruit/Adafruit_CircuitPython_SD#47]
attempting to use on raspberry pi using https://learn.adafruit.com/circuitpython-on-raspberrypi-linux?gclid=EAIaIQobChMIr8zA54ak9wIVQ__jBx2CfgkJEAAYASAAEgKCyPD_BwE

ran python3 -m pip install adafruit-circuitpython-sd

and then tried to use example but cannot find storage? please advise.

**Comment by dhalbert** [comment]
This is for use on an SPI bus connected to an SD card. On a Raspberry Pi, you can simply use an SD card to USB adapter, and use regular file-based I/O that is a part of Python (`open()`, etc.)

**Comment by dhalbert** [comment]
For more support, ask on https://adafru.it/discord or https://forums.adafruit.com. GitHub is for bug or enhancement requests.

**Comment by HourGlss** [comment]
No. I am not attempting to use the SD CARD slot, I am trying to use an additional sdcard via spi. I want to use the storage module. I understand that there is an SD CARD. OBVIOUSLY there is an sd card. https://docs.circuitpython.org/en/latest/shared-bindings/index.html that indicates that storage is available on raspberry pi 4 which I'm using.

it is not. Please reopen this issue as I believe it to be a bug. please do not simply close my issue without addressing it.

**Comment by dhalbert** [comment]
`storage` is not available via Blinka. Please ask for further support in discord or the forums. It's not a bug in this library.

**Comment by dhalbert** [comment]
Your edited comment makes things clearer, but it's still the case that `storage` is not available on Blinka. Equivalent functionality to talk to a second SD card is available using an SD card adapter plugged into a USB port, so you don't need to wire up SPI to talk to an SD card.

**Comment by HourGlss** [comment]
I dont want to use an sdcard adapter it has to work via spi.

**Comment by dhalbert** [comment]
Let's discuss this in discord please.

**Comment by HourGlss** [comment]
any idea on where i can find the github issues page for the https://docs.circuitpython.org/en/latest/shared-bindings/support_matrix.html page?

**Comment by dhalbert** [comment]
resolved in discord
